### ISSUE TITLE
Need to import eea.graylogger

### ISSUE THREAD

**Issue by Gomez** [eea/eea.graylogger#2]
I got this error:

```
xxx@robert:~/buildouts/hsorga$ bin/zeoclient1 fg
Error: unknown type name: 'graylog'
(line 17 in file:///home/xxx/buildouts/hsorga/parts/zeoclient1/etc/zope.conf)
For help, use bin/zeoclient1 -h
```

After adding `%import eea.graylogger` it worked:

```
zope-conf-imports =
  eea.graylogger

event-log-custom =
  %import eea.graylogger
  <graylog>
    server server.de:5140
  </graylog>
```

The raven addon from sentry does the same. Would be good to get it added to the docs.

**Comment by avoinea** [comment]
You need a newer version of **plone.recipe.zope2instance** (version `4.2.17+`) as `zope-conf-imports` is supposed to do the `%import`.

I'll will add it to the documentation within **Dependencies** section.
